name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Ver estrutura
        run: ls -R

      - name: Build backend
        run: |
          cd backend
          chmod +x mvnw
          ./mvnw clean package -DskipTests