name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Listar arquivos (Diagnóstico)
        run: ls -R  # Isso vai nos mostrar onde o pom.xml está de verdade nos logs do GitHub

      - name: Build do Backend
        # Aqui usamos o caminho relativo direto para o arquivo
        run: mvn -f backend/pom.xml clean install -DskipTests